### ISSUE TITLE
[feature] Add a transformer mode of operation with an External secrets file.

### ISSUE THREAD

**Issue by antoinemartin** [kaweezle/krmfnsops#14]
Havig the secrets in multiple files makes it complicated when the keys need to be managed (rotation, add/rm) and also can
lead to errors due to duplication. 

The idea is to have all the secrets located in a single yaml file, much like a helm values file, for instance `common/secrets.yaml` and have the sops transformer use it as a source for replacing values in resources.

The configuration would be like:

```yaml
spec:
  secretsFile: ../../common/secrets.yaml
  replacements:
   - target:
        kind: Secret
        name: github-private-repo-creds
     patches:
        - path:  stringData/password
          secretRef: secrets/github/password
          encoding: plain # or base64
```

Apart from the advantages linked to encryption management, it would allow to have plain normal kustomizations, only with the wrong secrets. Moreover, on some secrets, some values don't need to be encrypted (URLs, generic parameters...).

We could even reuse part of the code of the `patches` transformer.
